{% set name = "MetPy" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1f85f08642056bb6bdceec5febace10a6b7b2d71b77f3129505857c0eabdbce9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
    - setuptools_scm

  run:
    - python >=3.7
    - importlib_metadata >=1.0.0
    - importlib_resources >=1.3.0
    - matplotlib-base >=3.0.1
    - numpy >=1.17
    - pandas >=0.24.0
    - pint >=0.10.1
    - pooch >=0.1
    - pyproj >=2.3.0
    - scipy >=1.2.0
    - traitlets >=4.3.0
    - xarray >=0.14.1
    - cartopy >=0.17.0

test:
  imports:
    - metpy.calc
    - metpy.interpolate
    - metpy.io
    - metpy.plots
    - metpy.units

about:
  home: https://github.com/Unidata/MetPy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: MetPy is a collection of tools in Python for reading, visualizing and performing calculations with weather data.
  description: |
    The space MetPy aims for is GEMPAK (and maybe NCL)-like functionality,
    in a way that plugs easily into the existing scientific Python ecosystem
    (numpy, scipy, matplotlib). So, if you take the average GEMPAK script for
    a weather map, you need to: read data, calculate a derived field, and
    show on a map/skew-T. One of the benefits hoped to achieve over GEMPAK
    is to make it easier to use these routines for any meteorological Python
    application; this means making it easy to pull out the LCL calculation
    and just use that, or re-use the Skew-T with your own data code. MetPy
    also prides itself on being well-documented and well-tested, so that
    on-going maintenance is easily manageable.
  doc_url: https://unidata.github.io/MetPy
  dev_url: https://github.com/Unidata/MetPy

extra:
  recipe-maintainers:
    - dopplershift
    - dcamron
