{% set name = "MetPy" %}
{% set version = "0.9.1" %}
{% set sha256 = "2dadf750ddb752da13f4ece9b5784587c79c6c86f9a7be8d0cae3d236e403498" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{name[0]}}/{{name}}/{{name}}-{{version}}.tar.gz
  sha256: {{sha256}}

build:
    script: python setup.py install --single-version-externally-managed --record record.txt
    number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy >=1.10
    - scipy >=0.14.0
    - matplotlib >=1.4.0
    - pint >=0.8
    - pyproj >=1.9.4
    - xarray >=0.9.6
    - enum34  # [py27]

test:
  imports:
    - metpy.calc
    - metpy.plots
    - metpy.io
    - metpy.gridding

about:
  home: https://github.com/Unidata/MetPy
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'MetPy is a collection of tools in Python for reading, visualizing and performing calculations with weather data.'
  description: |
    The space MetPy aims for is GEMPAK (and maybe NCL)-like functionality,
    in a way that plugs easily into the existing scientific Python ecosystem
    (numpy, scipy, matplotlib). So, if you take the average GEMPAK script for
    a weather map, you need to: read data, calculate a derived field, and
    show on a map/skew-T. One of the benefits hoped to achieve over GEMPAK
    is to make it easier to use these routines for any meteorological Python
    application; this means making it easy to pull out the LCL calculation
    and just use that, or re-use the Skew-T with your own data code. MetPy
    also prides itself on being well-documented and well-tested, so that
    on-going maintenance is easily manageable.
  doc_url: https://unidata.github.io/MetPy
  dev_url: https://github.com/Unidata/MetPy

extra:
  recipe-maintainers:
    - dopplershift
    - jrleeman
