appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: gCydVXHgGeRPwrZ24KgFLc+eJwNGMr+0zPAbWKpRPePG5OwaZamnBPogcC43i6OjtcCJTKcheAZgoDwzmMGDJseJ9rF0anrwy+wU32o8Qk2PbAZXaxSEcwLK+MHKZk3qn1j/NMNDQqMIQd9g57lzeVWRsQ9MiOO7Zg1G7T5REWqaeoYHY9m50TfD0/9NpRTL9UqId2hI57F4ZMJynAkhJgQlrfjCeDLBuf8M5USjk2dnegahO5/ZxZljo5gvTLoLJdH8eErsJYCAUc1724iJuS9ODmYfPru6ypUDnC8qKEvkfDEGK/1uk6p9xq5qA5p4Q3N16cVrgET+CsByRDKiB0jDWI12U8PSSa7t8+DF/IukKa04Vm38cjuG7GHfajKa3ob0IcDwv5DuCoJymbhykNw6zNaek4Lj7d/0IBfgrkGnh5VYbbW73rnpjTsuyVEqGFhYUGGWShEZKslw9mq7UxztzhEVplDQG08di0zqQb18OxPAHlnp/t76VRSPz+lvoZvggO0eobqMVMdF/E1Fmb/A4C+8QLx4zK+FZaS513icWQgeZdR27L20hXtJbqNaIPjyPUV+vdvDb2QdnVgtGU0s1Y9PQ1FfL9bPqw+2ixMX9gJhpMZg3gB8yN7h38C+ZoTyNuXpSDdLVDTy0ebMA8FPCKOw9ixZCSEgYLDOyY4=}
provider:
  win: azure
conda_forge_output_validation: true
